### ISSUE TITLE
Assignment 1-9

### ISSUE THREAD

**Issue by victord3** [victord3/My_Project#3]

**Comment by belinskyc** [comment]
Everything looks good... 

**What did you mean by "(by index -- not by day)"** 
I took that part out.  I had it there because day 1 has a day number that is even (so, you could interpret the question as do 1,3,5,7,9... or 2,4,6,8,10).  To be honest, they both work for me!  

**in Q\#4, was I suppose to do it different or have them both run in the same for loop?**
Nope, I broke up the question into two separate questions.

A little challenge for you.  Redo this line:
[  for(last8 in 7:numDays)](https://github.com/victord3/My_Project/blob/d8cbac47f5d355ef89d9a554a61985b920462705/script/app1-9.r#L49)

So that it will go through the last 8 values of **_any sized vector_** (not just a vector with 14 values).

**Comment by victord3** [comment]
for(last8 in (numdays-8):numdays)

Would it be something like this?

**Comment by belinskyc** [comment]
So close... but remember sequences are inclusive of the numbers on both sides of the semicolon

**Comment by victord3** [comment]
for(last8 in seq(from=numDays, to=numDays-8, by=-1)
Like this with using sequence?

**Comment by belinskyc** [comment]
You're thinking too hard!

10-2 = 8
but, in between (and inclusive of) 2 and 10 is 9 numbers.

Your answer would give the last 9 values

**Comment by belinskyc** [comment]
On another note, I tried replying to the comment in email (as the email said I could), but it did not seem to work.  Do you reply within your email or go to GitHub?

**Comment by victord3** [comment]
I reply within github.

I think I have ran out of ideas for this one.

**Comment by belinskyc** [comment]
This will cycle through the last *9* days
for(last8 in (numdays-8):numdays)

This will cycle through the last *8* days
for(last8 in (numdays-7):numdays)

Because we are inclusive of the numbers on both ends of the semicolon...

And, yeah, reply in email does not seem to work -- that kind of stinks.  GitHub says it should work.

**Comment by victord3** [comment]
Okay! That makes total sense now. Thank you!

**Comment by belinskyc** [comment]
You're thinking too hard!

10-2 = 8
but, in between (and inclusive of) 2 and 10 is 9 numbers.

Your answer would give the last 9 values
