### ISSUE TITLE
App 1-12

### ISSUE THREAD

**Issue by victord3** [victord3/My_Project#6]
App 1-12 Completed

**Comment by belinskyc** [comment]
Uh oh, I cannot Source your code ... says something about not being able to open twoWeekWeatherData3.csv.  And, as always I am too lazy to fix the problem myself... and I sure ain't going to set a working directory!

**Comment by victord3** [comment]
What would I have to do so solve this?

**Comment by victord3** [comment]
Just added data/ in front of the file to change the directory

**Comment by belinskyc** [comment]
Another part of my constant struggle to go against all the bad programming practices that are taught in most R tutorials and classes...

This line technically does nothing when you Source the code (there are multiple examples in your script):
`  remainder(50, 9)`

Because, it calls the function remainder() and remainder() returns a value.  But you are not doing anything with the value -- neither printing nor storing the value.  So the return value just kind of goes to programming purgatory.  I realize this code works if you click Run but I want you thinking about how to write a complete script that saves/reports all values.  And, there is no Run button in most programming languages...

For the last question, values over 100 will be assigned "A" instead of the error message.  Also, the value 0 will give you an R error: _object 'number' not found_.

**Comment by victord3** [comment]
Okay! I more had those lines in there for myself to test my function but I have assigned them as examples.

Also I fixed the issues for valued over 100 and the 0 value.

**Comment by belinskyc** [comment]
You could (and probably should) still combine the two error statements -- you just need to do it at the top of the if-else structure.

I will leave that to you and let you move on in life.

By the way, the three function's lesson (12,13,13b) are being modified.  Not severely, but you might notice changes as you are going through them -- including the application questions.  I will let you answer the old or the new questions.
